// ── i18n (EN / FR) ──────────────────────────────────────────────────

const I18N = {
  en: {
    docTitle: "ER Overlay — Layout Editor",
    brandTitle: "Layout Editor",
    importLayout: "Import layout file",
    new: "New",
    exportLayout: "Export layout file",
    palette: "Palette",
    paletteHint: "Drag an item onto the grid.",
    text: "Text",
    items: "Items",
    properties: "Properties",
    propertiesHint: "Select a tile or configure the grid.",
    tile: "Tile",
    type: "Type",
    label: "Label",
    metric: "Metric",
    key: "Key",
    col: "Col",
    row: "Row",
    showMax: "show_max",
    trackEquipped: "track_equipped (highlight when equipped)",
    iconOptional: "Icon (optional)",
    iconPlaceholder: "kindling, scadutree…",
    delete: "Delete",
    grid: "Grid",
    columns: "Columns",
    rows: "Rows",
    gridResizeHint: "Drag grid edges to resize.",
    unitPx: "Unit (px)",
    gap: "Gap",
    padding: "Padding",
    defaultSection: "Default section",
    labelPalette: "Label (text)",
    defaultTitle: "TITLE",
    cat_runes: "Runes",
    cat_key_items: "Key items",
    cat_talismans: "Talismans",
    cat_consumables: "Consumables",
    searchCategory: "Search {category}…",
    gridInfo: "{cols}×{rows} · {count}",
    tileCount_one: "{n} tile",
    tileCount_other: "{n} tiles",
    resizeWiderCols: "Widen columns",
    resizeWiderRows: "Widen rows",
    resizeGrid: "Resize grid",
    resize: "Resize",
    exportComment: "# Generated by ER Overlay Layout Editor",
    exportImpossible: "Export failed:",
    exportNoTiles: "No tiles to export",
    exportOverlap: "{section}: overlapping tiles",
    exportOverflow:
      '{section}: "{name}" exceeds the grid ({col} + {w} > {columns} columns)',
    exportDefaultSectionEmpty:
      'Default section "{name}" is empty — add a tile or change the default section',
    confirmClear: "Clear the current layout?",
    bootError: "Startup error: {message}",
    langSwitch: "Language",
  },
  fr: {
    docTitle: "ER Overlay — Éditeur de layout",
    brandTitle: "Éditeur de layout",
    importLayout: "Importer un fichier de layout",
    new: "Nouveau",
    exportLayout: "Exporter le fichier de layout",
    palette: "Palette",
    paletteHint: "Glissez un élément sur la grille.",
    text: "Texte",
    items: "Items",
    properties: "Propriétés",
    propertiesHint: "Sélectionnez une tuile ou configurez la grille.",
    tile: "Tuile",
    type: "Type",
    label: "Label",
    metric: "Métrique",
    key: "Clé (key)",
    col: "Col",
    row: "Row",
    showMax: "show_max",
    trackEquipped: "track_equipped (surbrillance si équipé)",
    iconOptional: "Icon (optionnel)",
    iconPlaceholder: "kindling, scadutree…",
    delete: "Supprimer",
    grid: "Grille",
    columns: "Colonnes",
    rows: "Lignes",
    gridResizeHint: "Glissez les bords de la grille pour redimensionner.",
    unitPx: "Unit (px)",
    gap: "Gap",
    padding: "Padding",
    defaultSection: "Section par défaut",
    labelPalette: "Label (texte)",
    defaultTitle: "TITRE",
    cat_runes: "Runes",
    cat_key_items: "Objets clés",
    cat_talismans: "Talismans",
    cat_consumables: "Consommables",
    searchCategory: "Rechercher {category}…",
    gridInfo: "{cols}×{rows} · {count}",
    tileCount_one: "{n} tuile",
    tileCount_other: "{n} tuiles",
    resizeWiderCols: "Élargir colonnes",
    resizeWiderRows: "Élargir lignes",
    resizeGrid: "Élargir la grille",
    resize: "Redimensionner",
    exportComment: "# Généré par ER Overlay Layout Editor",
    exportImpossible: "Export impossible :",
    exportNoTiles: "Aucune tuile à exporter",
    exportOverlap: "{section} : tuiles qui se chevauchent",
    exportOverflow:
      '{section} : « {name} » dépasse la grille ({col} + {w} > {columns} colonnes)',
    exportDefaultSectionEmpty:
      'Section par défaut « {name} » vide — ajoutez une tuile ou changez la section par défaut',
    confirmClear: "Effacer le layout actuel ?",
    bootError: "Erreur au démarrage : {message}",
    langSwitch: "Langue",
  },
};

const STORAGE_KEY = "er-layout-editor-lang";

let locale =
  localStorage.getItem(STORAGE_KEY) ||
  (navigator.language.toLowerCase().startsWith("fr") ? "fr" : "en");

if (!I18N[locale]) locale = "en";

function t(key, params = {}) {
  let s = I18N[locale][key] ?? I18N.en[key] ?? key;
  for (const [k, v] of Object.entries(params)) {
    s = s.split(`{${k}}`).join(String(v));
  }
  return s;
}

function tileCountLabel(n) {
  const key = n === 1 ? "tileCount_one" : "tileCount_other";
  return t(key, { n });
}

function setLocale(lang) {
  if (!I18N[lang] || lang === locale) return;
  locale = lang;
  localStorage.setItem(STORAGE_KEY, lang);
  document.documentElement.lang = lang;
  applyStaticI18n();
  if (typeof window.onLocaleChange === "function") window.onLocaleChange();
}

function applyStaticI18n() {
  document.title = t("docTitle");
  document.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    el.setAttribute("aria-label", t(el.dataset.i18nAria));
  });
  document.querySelectorAll(".lang-btn").forEach((btn) => {
    btn.classList.toggle("active", btn.dataset.lang === locale);
    btn.setAttribute("aria-pressed", btn.dataset.lang === locale ? "true" : "false");
  });
}

function initI18n() {
  document.documentElement.lang = locale;
  applyStaticI18n();
  document.querySelectorAll(".lang-btn").forEach((btn) => {
    btn.addEventListener("click", () => setLocale(btn.dataset.lang));
  });
}

initI18n();
