show_debug = false
anchor = "top-right"
offset_x = 16.0
offset_y = 16.0
scale = 1.0
text_size = 18.0
icon_size = 24.0
background_opacity = 0.65
gray_tint = 0.40
use_item_icons = true
# icons_dir = "assets/icons"   # relative to the er_overlay.dll directory
layout_file = "layouts/test.toml"
layout_section_hotkey = "F8"
default_layout_section = "minimalist"
