using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using SoulsFormats;
using SoulsFormats.Cryptography;

const int CategoryAccessory = 0x20000000;
const int CategoryGoods = 0x40000000;
const int ItemLotCategoryAccessory = 4;
const int ItemLotCategoryGoods = 1;

if (args.Length > 0 && args[0] == "--bootstrap")
{
    return BootstrapGoods(args);
}
if (args.Length > 0 && args[0] == "--probe-item")
{
    return ProbeItem(args);
}

return ExtractRuntimeFlags(args);

static int ExtractRuntimeFlags(string[] args)
{
    if (args.Length < 3)
    {
        Console.Error.WriteLine(
            "Usage: er_checks_extractor <regulation.bin> <checks.toml> <out lot_flags.toml> [oodle_dir] [--goods goods.toml] [--layout layout.toml|--layouts layouts_dir]");
        return 1;
    }

    var regPath = args[0];
    var checksPath = args[1];
    var outPath = Path.GetFullPath(args[2]);
    var options = ParseOptions(args, 3);

    if (!File.Exists(regPath))
    {
        Console.Error.WriteLine($"Missing regulation.bin: {regPath}");
        return 1;
    }
    if (!File.Exists(checksPath))
    {
        Console.Error.WriteLine($"Missing checks.toml: {checksPath}");
        return 1;
    }

    var wanted = ParseWantedChecks(checksPath);
    var historicKeys = ParseHistoricLayoutKeys(options.LayoutPaths);
    var historicGoods = new List<RuntimeGood>();
    if (historicKeys.Count > 0)
        historicGoods = ParseRuntimeHistoricGoods(LoadGoodsToml(options.GoodsPath), historicKeys);

    var distinct = wanted.Distinct().ToList();
    var regBytes = File.ReadAllBytes(regPath);
    var hash = Convert.ToHexString(SHA256.HashData(regBytes)).ToLowerInvariant();

    var resolved = 0;
    var untraceable = 0;
    var missing = 0;
    var mapFlags = new SortedDictionary<int, uint>();
    var enemyFlags = new SortedDictionary<int, uint>();
    var goodFlags = new SortedDictionary<string, uint>();

    if (distinct.Count > 0 || historicGoods.Count > 0)
    {
        if (!EnsureOodleDll(Path.GetDirectoryName(Path.GetFullPath(regPath)) ?? ".", options.OodleDir))
        {
            Console.Error.WriteLine(
                "Could not locate oo2core_*.dll (needed to decompress regulation.bin). "
                    + "Pass the game directory as the 4th argument.");
            return 3;
        }

        var itemLots = LoadItemLots(regPath);
        foreach (var lot in distinct)
        {
            var param = lot.Table == LotTable.Map ? itemLots.Map : itemLots.Enemy;
            var row = param?[lot.LotId];
            if (row is null)
            {
                Console.Error.WriteLine($"warn: {lot.TableName} lot {lot.LotId} not found in regulation");
                missing++;
                continue;
            }

            var flag = ReadLotFlag(row);
            if (flag == 0)
            {
                untraceable++;
                continue;
            }

            if (lot.Table == LotTable.Map)
                mapFlags[lot.LotId] = flag;
            else
                enemyFlags[lot.LotId] = flag;
            resolved++;
        }

        foreach (var good in historicGoods)
        {
            var matches = FindLotsForRuntimeGood(itemLots, good).ToList();
            if (matches.Count == 1)
            {
                goodFlags[good.Key] = matches[0].VanillaFlag;
                resolved++;
            }
            else if (matches.Count == 0)
            {
                Console.Error.WriteLine($"warn: historic good {good.Key} ({good.ItemId}) not found in current regulation");
                missing++;
            }
            else
            {
                Console.Error.WriteLine(
                    "warn: historic good "
                        + $"{good.Key} is ambiguous in current regulation: "
                        + string.Join(
                            ", ",
                            matches.Select(m =>
                                $"{m.TableName}:{m.LotId}/cat={m.ItemLotCategory}/flag={m.VanillaFlag}"
                            )
                        )
                );
                untraceable++;
            }
        }
    }

    var sb = new StringBuilder();
    sb.AppendLine("# Generated by er_checks_extractor. Do not edit by hand.");
    sb.AppendLine($"regulation_sha256 = \"{hash}\"");
    AppendFlagsSection(sb, "map", mapFlags);
    AppendFlagsSection(sb, "enemy", enemyFlags);
    AppendGoodsSection(sb, goodFlags);
    File.WriteAllText(outPath, sb.ToString());
    Console.WriteLine(
        $"Wrote {outPath}: {resolved} resolved, {untraceable} untraceable, {missing} missing (of {distinct.Count} check lots + {historicGoods.Count} historic goods).");
    return 0;
}

static int BootstrapGoods(string[] args)
{
    if (args.Length < 5)
    {
        Console.Error.WriteLine(
            "Usage: er_checks_extractor --bootstrap <vanilla regulation.bin> <goods.toml> <layout.toml|layouts_dir> <out goods.toml> [oodle_dir]");
        return 1;
    }

    var regPath = args[1];
    var goodsPath = args[2];
    var layoutPath = args[3];
    var outGoodsPath = Path.GetFullPath(args[4]);
    var oodleDir = args.Length > 5 ? args[5] : null;

    if (!File.Exists(regPath))
    {
        Console.Error.WriteLine($"Missing regulation.bin: {regPath}");
        return 1;
    }
    var goodsToml = LoadGoodsToml(goodsPath);

    _ = layoutPath; // Kept for CLI compatibility; bootstrap enriches all unique goods.

    if (!EnsureOodleDll(Path.GetDirectoryName(Path.GetFullPath(regPath)) ?? ".", oodleDir))
    {
        Console.Error.WriteLine("Could not locate oo2core_*.dll (needed to decompress regulation.bin).");
        return 3;
    }

    var itemLots = LoadItemLots(regPath);
    var goods = ParseBootstrapGoods(goodsToml);
    var resolved = new Dictionary<string, LotMetadata>();
    var conflicts = 0;
    var missing = 0;

    foreach (var good in goods)
    {
        if (good.HistoricLot is LotMetadata existing)
        {
            resolved[good.Key] = existing;
            continue;
        }

        var matches = FindLotsForItem(itemLots, good).ToList();
        if (matches.Count == 1)
        {
            resolved[good.Key] = matches[0];
        }
        else if (matches.Count > 1)
        {
            conflicts++;
            Console.Error.WriteLine(
                "warn: ambiguous vanilla lot for "
                    + $"{good.Key}: {matches.Count} candidates: "
                    + string.Join(
                        ", ",
                        matches.Select(m =>
                            $"{m.TableName}:{m.LotId}/cat={m.ItemLotCategory}/flag={m.VanillaFlag}"
                        )
                    )
            );
        }
        else
        {
            missing++;
            Console.Error.WriteLine($"warn: no vanilla lot found for {good.Key} ({good.ItemId})");
        }
    }

    WriteEnrichedGoodsToml(goodsPath, outGoodsPath, resolved);
    Console.WriteLine(
        $"Wrote {outGoodsPath}: {resolved.Count} historic lot entries present, {conflicts} ambiguous, {missing} missing.");
    return 0;
}

static int ProbeItem(string[] args)
{
    if (args.Length < 4)
    {
        Console.Error.WriteLine(
            "Usage: er_checks_extractor --probe-item <regulation.bin> <item_id> <category:goods|accessory|any> [oodle_dir]");
        return 1;
    }

    var regPath = args[1];
    if (!int.TryParse(args[2], out var itemId))
    {
        Console.Error.WriteLine($"Invalid item_id: {args[2]}");
        return 1;
    }
    int? category = args[3].Equals("any", StringComparison.OrdinalIgnoreCase)
        ? null
        : args[3].Equals("accessory", StringComparison.OrdinalIgnoreCase)
            ? CategoryAccessory
            : CategoryGoods;
    var oodleDir = args.Length > 4 ? args[4] : null;

    if (!File.Exists(regPath))
    {
        Console.Error.WriteLine($"Missing regulation.bin: {regPath}");
        return 1;
    }
    if (!EnsureOodleDll(Path.GetDirectoryName(Path.GetFullPath(regPath)) ?? ".", oodleDir))
    {
        Console.Error.WriteLine("Could not locate oo2core_*.dll (needed to decompress regulation.bin).");
        return 3;
    }

    var itemLots = LoadItemLots(regPath);
    var matches = FindLotsForItemDebug(itemLots.Map, LotTable.Map, itemId, category)
        .Concat(FindLotsForItemDebug(itemLots.Enemy, LotTable.Enemy, itemId, category))
        .ToList();

    Console.WriteLine($"item_id = {itemId}");
    Console.WriteLine($"category = {CategoryName(category)}");
    Console.WriteLine($"matches = {matches.Count}");
    foreach (var m in matches)
    {
        Console.WriteLine(
            $"table={m.TableName} lot_id={m.LotId} slot={m.Slot:D2} lot_category={m.ItemLotCategory} getItemFlagId={m.VanillaFlag}");
    }
    return matches.Count == 0 ? 2 : 0;
}

static List<LotRequest> ParseWantedChecks(string path)
{
    var result = new List<LotRequest>();
    var inCheck = false;
    var dynamic = false;
    int? lotId = null;

    void Flush()
    {
        if (inCheck && dynamic && lotId is int id)
            result.Add(new LotRequest(LotTable.Map, id));
        dynamic = false;
        lotId = null;
    }

    foreach (var raw in File.ReadLines(path))
    {
        var line = StripComment(raw).Trim();
        if (line.StartsWith("[["))
        {
            Flush();
            inCheck = line.Equals("[[check]]", StringComparison.OrdinalIgnoreCase);
            continue;
        }
        if (!inCheck || line.Length == 0)
            continue;

        var (key, val) = SplitKeyValue(line);
        switch (key)
        {
            case "dynamic":
                dynamic = val!.StartsWith("true", StringComparison.OrdinalIgnoreCase);
                break;
            case "lot_id":
                if (int.TryParse(val, out var v))
                    lotId = v;
                break;
        }
    }

    Flush();
    return result;
}

static HashSet<string> ParseHistoricLayoutKeys(IEnumerable<string> paths)
{
    var result = new HashSet<string>();
    foreach (var path in paths)
    {
        if (!File.Exists(path))
            continue;
        var inTile = false;
        string? key = null;
        var historic = false;

        void Flush()
        {
            if (inTile && historic && !string.IsNullOrWhiteSpace(key))
                result.Add(key);
            key = null;
            historic = false;
        }

        foreach (var raw in File.ReadLines(path))
        {
            var line = StripComment(raw).Trim();
            if (line.Length == 0)
                continue;
            if (line.StartsWith("[["))
            {
                Flush();
                inTile = line.Equals("[[tile]]", StringComparison.OrdinalIgnoreCase)
                    || line.Equals("[[section.tile]]", StringComparison.OrdinalIgnoreCase);
                continue;
            }
            if (!inTile)
                continue;
            var (k, v) = SplitKeyValue(line);
            if (k == "key")
                key = Unquote(v!);
            else if (k == "historic")
                historic = v!.StartsWith("true", StringComparison.OrdinalIgnoreCase);
        }
        Flush();
    }
    return result;
}

static List<RuntimeGood> ParseRuntimeHistoricGoods(string goodsToml, HashSet<string> historicKeys)
{
    if (historicKeys.Count == 0)
        return [];

    return ParseGoodBlocks(goodsToml)
        .Where(g => historicKeys.Contains(g.Key) && !g.Count)
        .Select(g => new RuntimeGood(g.Key, g.ItemId, g.Category))
        .ToList();
}

static List<BootstrapGood> ParseBootstrapGoods(string goodsToml)
{
    return ParseGoodBlocks(goodsToml)
        .Where(g => !g.Count)
        .Select(g => new BootstrapGood(g.Key, g.ItemId, g.Category, g.HistoricLot))
        .ToList();
}

static List<GoodBlock> ParseGoodBlocks(string rawToml)
{
    var result = new List<GoodBlock>();
    var inGood = false;
    string? key = null;
    int? itemId = null;
    var category = CategoryGoods;
    LotMetadata? historicLot = null;
    var count = false;
    LotTable? historicLotTable = null;
    int? historicLotId = null;
    uint? historicVanillaFlag = null;

    void Flush()
    {
        historicLot ??= BuildHistoricLot(historicLotTable, historicLotId, historicVanillaFlag);
        if (inGood && key is not null && itemId is int id)
            result.Add(new GoodBlock(key, id, category, count, historicLot));
        key = null;
        itemId = null;
        category = CategoryGoods;
        historicLot = null;
        count = false;
        historicLotTable = null;
        historicLotId = null;
        historicVanillaFlag = null;
    }

    foreach (var raw in ReadLines(rawToml))
    {
        var line = StripComment(raw).Trim();
        if (line.Length == 0)
            continue;
        if (line.StartsWith("[["))
        {
            Flush();
            inGood = line.Equals("[[good]]", StringComparison.OrdinalIgnoreCase);
            continue;
        }
        if (!inGood)
            continue;
        var (k, v) = SplitKeyValue(line);
        switch (k)
        {
            case "key":
                key = Unquote(v!);
                break;
            case "item_id":
                if (int.TryParse(v, out var id))
                    itemId = id;
                break;
            case "category":
                category = Unquote(v!).Equals("accessory", StringComparison.OrdinalIgnoreCase)
                    ? CategoryAccessory
                    : CategoryGoods;
                break;
            case "historic_lot":
                historicLot = ParseHistoricLotInline(v!);
                break;
            case "historic_lot_table":
                historicLotTable = Unquote(v!).Equals("enemy", StringComparison.OrdinalIgnoreCase)
                    ? LotTable.Enemy
                    : LotTable.Map;
                break;
            case "historic_lot_id":
                if (int.TryParse(v, out var lotId))
                    historicLotId = lotId;
                break;
            case "historic_vanilla_flag":
                if (uint.TryParse(v, out var flag))
                    historicVanillaFlag = flag;
                break;
            case "count":
                count = v!.StartsWith("true", StringComparison.OrdinalIgnoreCase);
                break;
        }
    }
    Flush();
    return result;
}

static LotMetadata? BuildHistoricLot(LotTable? table, int? lotId, uint? vanillaFlag)
{
    if (table is not LotTable t || lotId is not int id || vanillaFlag is not uint flag)
        return null;
    return new LotMetadata(t, id, flag);
}

static LotMetadata? ParseHistoricLotInline(string raw)
{
    var tableMatch = Regex.Match(raw, "table\\s*=\\s*\"(?<table>[^\"]+)\"");
    var lotMatch = Regex.Match(raw, "lot_id\\s*=\\s*(?<id>\\d+)");
    var flagMatch = Regex.Match(raw, "vanilla_flag\\s*=\\s*(?<flag>\\d+)");
    if (!tableMatch.Success || !lotMatch.Success || !flagMatch.Success)
        return null;
    var table = tableMatch.Groups["table"].Value.Equals("enemy", StringComparison.OrdinalIgnoreCase)
        ? LotTable.Enemy
        : LotTable.Map;
    return new LotMetadata(
        table,
        int.Parse(lotMatch.Groups["id"].Value),
        uint.Parse(flagMatch.Groups["flag"].Value));
}

static IEnumerable<LotMetadata> FindLotsForItem(ItemLots itemLots, BootstrapGood good)
{
    foreach (var match in FindLotsForItemInParam(itemLots.Map, LotTable.Map, good.ItemId, good.Category))
        yield return match;
    foreach (var match in FindLotsForItemInParam(itemLots.Enemy, LotTable.Enemy, good.ItemId, good.Category))
        yield return match;
}

static IEnumerable<LotMetadata> FindLotsForRuntimeGood(ItemLots itemLots, RuntimeGood good)
{
    foreach (var match in FindLotsForItemInParam(itemLots.Map, LotTable.Map, good.ItemId, good.Category))
        yield return match;
    foreach (var match in FindLotsForItemInParam(itemLots.Enemy, LotTable.Enemy, good.ItemId, good.Category))
        yield return match;
}

static IEnumerable<LotMetadata> FindLotsForItemInParam(PARAM? param, LotTable table, int targetItemId, int targetCategory)
{
    if (param is null)
        yield break;
    foreach (var row in param.Rows)
    {
        for (var slot = 1; slot <= 8; slot++)
        {
            var suffix = slot.ToString("D2");
            var itemId = Convert.ToInt32(row[$"lotItemId{suffix}"].Value);
            var category = Convert.ToInt32(row[$"lotItemCategory{suffix}"].Value);
            if (!ItemIdMatches(itemId, targetItemId, targetCategory) || !CategoryMatches(category, targetCategory))
                continue;

            var flag = ReadLotFlag(row);
            if (flag != 0)
                yield return new LotMetadata(table, row.ID, flag, category);
        }
    }
}

static IEnumerable<LotDebugMatch> FindLotsForItemDebug(PARAM? param, LotTable table, int targetItemId, int? targetCategory)
{
    if (param is null)
        yield break;
    foreach (var row in param.Rows)
    {
        for (var slot = 1; slot <= 8; slot++)
        {
            var suffix = slot.ToString("D2");
            var itemId = Convert.ToInt32(row[$"lotItemId{suffix}"].Value);
            var category = Convert.ToInt32(row[$"lotItemCategory{suffix}"].Value);
            if (!ItemIdMatches(itemId, targetItemId, targetCategory) || !CategoryMatches(category, targetCategory))
                continue;

            yield return new LotDebugMatch(table, row.ID, slot, ReadLotFlag(row), category);
        }
    }
}

static void WriteEnrichedGoodsToml(
    string inputPath,
    string outputPath,
    Dictionary<string, LotMetadata> resolved
)
{
    var output = new List<string>();
    var inGood = false;
    string? key = null;
    var block = new List<string>();

    void Flush()
    {
        if (inGood && key is not null && resolved.TryGetValue(key, out var meta))
        {
            var insertAt = block.FindIndex(l => l.TrimStart().StartsWith("icon_id", StringComparison.Ordinal));
            if (insertAt < 0)
                insertAt = block.Count;
            block.Insert(insertAt, $"historic_lot_table = \"{meta.TableName}\"");
            block.Insert(insertAt + 1, $"historic_lot_id = {meta.LotId}");
            block.Insert(insertAt + 2, $"historic_vanilla_flag = {meta.VanillaFlag}");
        }
        output.AddRange(block);
        block.Clear();
        key = null;
    }

    foreach (var raw in File.ReadLines(inputPath))
    {
        var trimmed = raw.Trim();
        if (trimmed.StartsWith("[["))
        {
            Flush();
            inGood = trimmed.Equals("[[good]]", StringComparison.OrdinalIgnoreCase);
        }
        if (inGood)
        {
            var (k, v) = SplitKeyValue(StripComment(raw).Trim());
            if (k is "historic_lot" or "historic_lot_table" or "historic_lot_id" or "historic_vanilla_flag")
                continue;
            if (k == "key")
                key = Unquote(v!);
        }
        block.Add(raw);
    }
    Flush();

    File.WriteAllText(outputPath, string.Join("\n", output) + "\n");
}

static string LoadGoodsToml(string? path)
{
    if (!string.IsNullOrWhiteSpace(path) && File.Exists(path))
        return File.ReadAllText(path);

    var asm = System.Reflection.Assembly.GetExecutingAssembly();
    using var stream = asm.GetManifestResourceStream("goods.toml")
        ?? throw new InvalidOperationException("Embedded goods.toml resource is missing");
    using var reader = new StreamReader(stream, Encoding.UTF8);
    return reader.ReadToEnd();
}

static IEnumerable<string> ReadLines(string raw)
{
    using var reader = new StringReader(raw);
    string? line;
    while ((line = reader.ReadLine()) is not null)
        yield return line;
}

static ItemLots LoadItemLots(string regPath)
{
    BND4 bnd;
    try
    {
        bnd = RegulationDecryptor.DecryptERRegulation(regPath);
    }
    catch (Exception e)
    {
        throw new InvalidOperationException($"Failed to read regulation.bin: {e.Message}", e);
    }

    PARAM? mapParam = null;
    PARAM? enemyParam = null;
    foreach (var file in bnd.Files)
    {
        if (file.Name.EndsWith("ItemLotParam_map.param", StringComparison.OrdinalIgnoreCase))
            mapParam = PARAM.Read(file.Bytes);
        else if (file.Name.EndsWith("ItemLotParam_enemy.param", StringComparison.OrdinalIgnoreCase))
            enemyParam = PARAM.Read(file.Bytes);
    }

    var def = LoadItemLotParamDef();
    mapParam?.ApplyParamdef(def);
    enemyParam?.ApplyParamdef(def);
    return new ItemLots(mapParam, enemyParam);
}

static uint ReadLotFlag(PARAM.Row row)
{
    return Convert.ToUInt32(row["getItemFlagId"].Value);
}

static bool ItemIdMatches(int lotItemId, int goodItemId, int? goodCategory)
{
    if (lotItemId == goodItemId)
        return true;
    return goodCategory switch
    {
        CategoryAccessory => lotItemId == (CategoryAccessory | goodItemId),
        CategoryGoods => lotItemId == (CategoryGoods | goodItemId),
        _ => false,
    };
}

static bool CategoryMatches(int lotCategory, int? goodCategory)
{
    if (goodCategory is null)
        return true;
    return goodCategory switch
    {
        CategoryAccessory => lotCategory is CategoryAccessory or ItemLotCategoryAccessory,
        CategoryGoods => lotCategory is CategoryGoods or ItemLotCategoryGoods,
        _ => lotCategory == goodCategory,
    };
}

static string CategoryName(int? category)
{
    return category switch
    {
        null => "any",
        CategoryAccessory => "accessory",
        CategoryGoods => "goods",
        _ => category.Value.ToString(),
    };
}

static void AppendFlagsSection(StringBuilder sb, string name, SortedDictionary<int, uint> flags)
{
    sb.AppendLine();
    sb.AppendLine($"[{name}]");
    foreach (var (lot, flag) in flags)
        sb.AppendLine($"{lot} = {flag}");
}

static void AppendGoodsSection(StringBuilder sb, SortedDictionary<string, uint> flags)
{
    sb.AppendLine();
    sb.AppendLine("[goods]");
    foreach (var (key, flag) in flags)
        sb.AppendLine($"{key} = {flag}");
}

static ExtractOptions ParseOptions(string[] args, int start)
{
    string? oodleDir = null;
    string? goodsPath = null;
    var layoutPaths = new List<string>();
    for (var i = start; i < args.Length; i++)
    {
        switch (args[i])
        {
            case "--goods" when i + 1 < args.Length:
                goodsPath = args[++i];
                break;
            case "--layout" when i + 1 < args.Length:
                layoutPaths.Add(args[++i]);
                break;
            case "--layouts" when i + 1 < args.Length:
                layoutPaths.AddRange(ResolveLayoutPaths(args[++i]));
                break;
            default:
                if (oodleDir is null)
                    oodleDir = args[i];
                break;
        }
    }
    return new ExtractOptions(oodleDir, goodsPath, layoutPaths);
}

static List<string> ResolveLayoutPaths(string path)
{
    if (Directory.Exists(path))
        return Directory.GetFiles(path, "*.toml").ToList();
    return File.Exists(path) ? [path] : [];
}

static (string? Key, string? Value) SplitKeyValue(string line)
{
    var eq = line.IndexOf('=');
    if (eq < 0)
        return (null, null);
    return (line[..eq].Trim(), line[(eq + 1)..].Trim());
}

static string StripComment(string line)
{
    var inString = false;
    for (var i = 0; i < line.Length; i++)
    {
        if (line[i] == '"')
            inString = !inString;
        else if (line[i] == '#' && !inString)
            return line[..i];
    }
    return line;
}

static string Unquote(string raw)
{
    var v = raw.Trim();
    return v.Length >= 2 && v[0] == '"' && v[^1] == '"' ? v[1..^1] : v;
}

static PARAMDEF LoadItemLotParamDef()
{
    var asm = System.Reflection.Assembly.GetExecutingAssembly();
    using var stream = asm.GetManifestResourceStream("ItemLotParam.xml")
        ?? throw new InvalidOperationException("Embedded ItemLotParam.xml resource is missing");

    var tmp = Path.Combine(Path.GetTempPath(), $"er_itemlotparam_{Guid.NewGuid():N}.xml");
    try
    {
        using (var fs = File.Create(tmp))
            stream.CopyTo(fs);
        return PARAMDEF.XmlDeserialize(tmp, true);
    }
    finally
    {
        try
        {
            File.Delete(tmp);
        }
        catch
        {
            // Best-effort cleanup of the temp paramdef.
        }
    }
}

static bool EnsureOodleDll(string regulationDir, string? explicitDir)
{
    var exeDir = AppContext.BaseDirectory;

    if (Directory.GetFiles(exeDir, "oo2core_*.dll").Length == 0)
    {
        foreach (var dir in CandidateDirs(regulationDir, explicitDir))
        {
            if (!Directory.Exists(dir))
                continue;
            var src = Directory.GetFiles(dir, "oo2core_*.dll").FirstOrDefault();
            if (src is not null)
            {
                File.Copy(src, Path.Combine(exeDir, Path.GetFileName(src)), overwrite: true);
                break;
            }
        }
    }

    if (Directory.GetFiles(exeDir, "oo2core_*.dll").Length == 0)
        return false;
    Directory.SetCurrentDirectory(exeDir);
    return true;
}

static IEnumerable<string> CandidateDirs(string regulationDir, string? explicitDir)
{
    yield return AppContext.BaseDirectory;
    if (!string.IsNullOrWhiteSpace(explicitDir))
        yield return explicitDir;

    var dir = new DirectoryInfo(regulationDir);
    while (dir is not null)
    {
        yield return dir.FullName;
        dir = dir.Parent;
    }
}

enum LotTable
{
    Map,
    Enemy,
}

readonly record struct LotRequest(LotTable Table, int LotId)
{
    public string TableName => Table == LotTable.Map ? "map" : "enemy";
}

readonly record struct LotMetadata(LotTable Table, int LotId, uint VanillaFlag, int ItemLotCategory = -1)
{
    public string TableName => Table == LotTable.Map ? "map" : "enemy";
}

readonly record struct LotDebugMatch(
    LotTable Table,
    int LotId,
    int Slot,
    uint VanillaFlag,
    int ItemLotCategory
)
{
    public string TableName => Table == LotTable.Map ? "map" : "enemy";
}

readonly record struct GoodBlock(string Key, int ItemId, int Category, bool Count, LotMetadata? HistoricLot);

readonly record struct BootstrapGood(string Key, int ItemId, int Category, LotMetadata? HistoricLot);

readonly record struct RuntimeGood(string Key, int ItemId, int Category);

readonly record struct ItemLots(PARAM? Map, PARAM? Enemy);

readonly record struct ExtractOptions(string? OodleDir, string? GoodsPath, List<string> LayoutPaths);
