// er_checks_extractor: shipped companion that resolves the current event flag of each
// "dynamic" check (randomized ground loot) from a modded regulation.bin.
//
// Why it exists
// -------------
// The item randomizer relocates world loot, so the acquisition flag (getItemFlagId) at a given
// pickup spot changes every seed. The overlay can only track a *spot* reliably through the stable
// ItemLotParam Row ID (the "lot_id"). This tool reads the regulation the game currently loads and,
// for each lot_id, reports the flag that is set when you grab whatever item sits there this seed.
//
// Pipeline
// --------
//   1. Parse checks.toml -> the list of dynamic map lots we care about (lot_id).
//   2. Decrypt + decompress the regulation.bin (BND4 archive) using the game's Oodle DLL.
//   3. Read ItemLotParam_map and apply the (embedded) paramdef.
//   4. For each wanted lot_id, read its current getItemFlagId.
//   5. Write checks_flags.toml: "lot_id = flag" lines + the regulation SHA-256.
//
// The overlay regenerates this file only when the regulation changes (it compares the hash/mtime),
// then hot-reloads it to update the checks panel. The user never runs this tool by hand.
//
// Isolated by design: the ItemLotParam paramdef is embedded in the exe (see LoadItemLotParamDef),
// so there is no dependency on a Smithbox install at runtime.

using System.Security.Cryptography;
using System.Text;
using SoulsFormats;

// CLI arguments (all provided automatically by the overlay):
//   args[0] regPath    : path to the regulation.bin the game LOADS (the ModEngine mod), to read.
//   args[1] checksPath : path to checks.toml, the master check list (tells us which lots to look up).
//   args[2] outPath    : where to write the resulting checks_flags.toml.
//   args[3] oodleDir   : (optional) directory holding oo2core_*.dll, i.e. the game install folder.
if (args.Length < 3)
{
    Console.Error.WriteLine(
        "Usage: er_checks_extractor <regulation.bin> <checks.toml> <out checks_flags.toml> [oodle_dir]");
    return 1;
}

// regPath: the modded regulation.bin we parse to discover this seed's flags (input, read-only).
var regPath = args[0];
// checksPath: checks.toml, the catalog of checks; we only extract its dynamic entries (input).
var checksPath = args[1];
// outPath: the checks_flags.toml we produce. Resolved to an absolute path now, because
// EnsureOodleDll below changes the process working directory (to where the Oodle DLL lives).
var outPath = Path.GetFullPath(args[2]);
// oodleDir: optional directory to find oo2core_*.dll (the game install dir). The overlay passes it
// because a ModEngine regulation.bin usually lives away from the game's Oodle DLL.
var oodleDir = args.Length > 3 ? args[3] : null;

if (!File.Exists(regPath))
{
    Console.Error.WriteLine($"Missing regulation.bin: {regPath}");
    return 1;
}
if (!File.Exists(checksPath))
{
    Console.Error.WriteLine($"Missing checks.toml: {checksPath}");
    return 1;
}

// Step 1: only the dynamic checks need resolving; everything else has a fixed flag in checks.toml.
var wanted = ParseWantedLots(checksPath);

// Hash the regulation so the overlay can tell whether checks_flags.toml is still for this seed.
var regBytes = File.ReadAllBytes(regPath);
var hash = Convert.ToHexString(SHA256.HashData(regBytes)).ToLowerInvariant();

var sb = new StringBuilder();
sb.AppendLine("# Generated by er_checks_extractor. Do not edit by hand.");
sb.AppendLine($"regulation_sha256 = \"{hash}\"");
sb.AppendLine();
sb.AppendLine("[flags]");

// Counters reported at the end:
//   resolved    : lots whose current flag was found and written.
//   untraceable : lots whose item this seed has no acquisition flag (flag == 0) -> can't be tracked.
//   missing     : lots not present in the regulation at all (stale/foreign checks.toml).
int resolved = 0, untraceable = 0, missing = 0;

// Skip the whole (expensive) regulation parse when there is nothing dynamic to resolve.
if (wanted.Count > 0)
{
    // Step 2a: make the game's Oodle DLL reachable; required to decompress the regulation.
    if (!EnsureOodleDll(Path.GetDirectoryName(Path.GetFullPath(regPath)) ?? ".", oodleDir))
    {
        Console.Error.WriteLine(
            "Could not locate oo2core_*.dll (needed to decompress regulation.bin). "
                + "Pass the game directory as the 4th argument.");
        return 3;
    }

    // Step 2b: decrypt + decompress the regulation into its inner BND4 archive of .param files.
    BND4 bnd;
    try
    {
        bnd = SFUtil.DecryptERRegulation(regBytes);
    }
    catch (Exception e)
    {
        Console.Error.WriteLine($"Failed to read regulation.bin: {e.Message}");
        return 3;
    }
    using var _bnd = bnd;

    // Step 3: pull the world/ground treasure item-lot table out of the archive.
    PARAM? mapParam = null;
    foreach (var file in bnd.Files)
    {
        if (file.Name.EndsWith("ItemLotParam_map.param", StringComparison.OrdinalIgnoreCase))
            mapParam = PARAM.ReadIgnoreCompression(file.Bytes);
    }

    // A param is just raw rows until a paramdef tells us the field layout (offsets/types/names).
    var def = LoadItemLotParamDef();
    mapParam?.ApplyParamdef(def);

    // Step 4: for each wanted lot, read the flag that flips when its current item is acquired.
    foreach (var lotId in wanted)
    {
        var row = mapParam?[lotId]; // PARAM indexer: look up the row by its (stable) Row ID.
        if (row is null)
        {
            Console.Error.WriteLine($"warn: map lot {lotId} not found in regulation");
            missing++;
            continue;
        }

        var flag = Convert.ToUInt32(row["getItemFlagId"].Value);
        if (flag == 0)
        {
            // Item placed here this seed has no acquisition flag (e.g. common/infinite item).
            untraceable++;
            continue;
        }

        sb.AppendLine($"{lotId} = {flag}");
        resolved++;
    }
}

// Step 5: always write the file (even with zero dynamic lots) so the overlay sees a fresh hash.
File.WriteAllText(outPath, sb.ToString());
Console.WriteLine(
    $"Wrote {outPath}: {resolved} resolved, {untraceable} untraceable, {missing} missing (of {wanted.Count} dynamic).");
return 0;

// Lightweight, dependency-free parse of checks.toml: collect lot_id of every
// [[check]] table whose `dynamic = true`. We don't pull in a full TOML library because the file
// is generated with a stable, one-key-per-line layout; we just scan it line by line.
//
// We track the current [[check]] block and remember its dynamic/lot_id fields, then
// "flush" (emit a result if it qualifies) when the next block header arrives or the file ends.
static List<int> ParseWantedLots(string path)
{
    var result = new List<int>();
    var inCheck = false; // are we inside a [[check]] table right now?
    var dynamic = false; // did this block declare dynamic = true?
    int? lotId = null; // the block's lot_id (the stable anchor), if any.

    // Commit the block we just finished reading, then reset for the next one.
    void Flush()
    {
        if (inCheck && dynamic && lotId is int id)
            result.Add(id);
        dynamic = false;
        lotId = null;
    }

    foreach (var raw in File.ReadLines(path))
    {
        var line = raw.Trim();

        // A new array-of-tables header ("[[check]]", "[[region]]", ...) ends the previous block.
        if (line.StartsWith("[["))
        {
            Flush();
            inCheck = line.Equals("[[check]]", StringComparison.OrdinalIgnoreCase);
            continue;
        }

        // Ignore lines outside a [[check]] block, blank lines, and comments.
        if (!inCheck || line.Length == 0 || line[0] == '#')
            continue;

        // Split "key = value" and read only the three fields we need.
        var eq = line.IndexOf('=');
        if (eq < 0)
            continue;
        var key = line[..eq].Trim();
        var val = line[(eq + 1)..].Trim();
        switch (key)
        {
            case "dynamic":
                dynamic = val.StartsWith("true", StringComparison.OrdinalIgnoreCase);
                break;
            case "lot_id":
                if (int.TryParse(val, out var v))
                    lotId = v;
                break;
        }
    }

    Flush(); // emit the final block (no trailing header to trigger it otherwise).
    return result;
}

// Loads the ItemLotParam paramdef from the embedded resource. PARAMDEF only deserializes from a
// file path, so the resource is spilled to a short-lived temp file (works under single-file publish).
static PARAMDEF LoadItemLotParamDef()
{
    var asm = System.Reflection.Assembly.GetExecutingAssembly();
    using var stream = asm.GetManifestResourceStream("ItemLotParam.xml")
        ?? throw new InvalidOperationException("Embedded ItemLotParam.xml resource is missing");

    var tmp = Path.Combine(Path.GetTempPath(), $"er_itemlotparam_{Guid.NewGuid():N}.xml");
    try
    {
        using (var fs = File.Create(tmp))
            stream.CopyTo(fs);
        return PARAMDEF.XmlDeserialize(tmp, true);
    }
    finally
    {
        try
        {
            File.Delete(tmp);
        }
        catch
        {
            // Best-effort cleanup of the temp paramdef.
        }
    }
}

// Makes oo2core_*.dll discoverable so SoulsFormats can decompress the regulation. SoulsFormats
// probes Directory.GetCurrentDirectory(), so we copy the DLL next to the exe and point the cwd
// there. Searches the exe dir, then an explicit dir (game install), then the regulation ancestors.
static bool EnsureOodleDll(string regulationDir, string? explicitDir)
{
    var exeDir = AppContext.BaseDirectory;

    if (Directory.GetFiles(exeDir, "oo2core_*.dll").Length == 0)
    {
        foreach (var dir in CandidateDirs(regulationDir, explicitDir))
        {
            if (!Directory.Exists(dir))
                continue;
            var src = Directory.GetFiles(dir, "oo2core_*.dll").FirstOrDefault();
            if (src is not null)
            {
                File.Copy(src, Path.Combine(exeDir, Path.GetFileName(src)), overwrite: true);
                break;
            }
        }
    }

    if (Directory.GetFiles(exeDir, "oo2core_*.dll").Length == 0)
        return false;

    Directory.SetCurrentDirectory(exeDir);
    return true;
}

static IEnumerable<string> CandidateDirs(string regulationDir, string? explicitDir)
{
    if (!string.IsNullOrEmpty(explicitDir))
        yield return explicitDir;

    var dir = new DirectoryInfo(regulationDir);
    for (var i = 0; i < 5 && dir is not null; i++, dir = dir.Parent)
        yield return dir.FullName;
}
